name: check reference metadata

on:
  merge_group:
  pull_request:

jobs:
  check-metadata:
    name: check metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/checkout@v4

      - run: cargo run -- configuration serve &

      - run: curl -X POST localhost:9100 -d "@example/metadata.json" > example/updated.json

      - run: diff example/metadata.json example/updated.json
