name: cargo machete

on:
  merge_group:
  pull_request:

jobs:
  cargo-machete:
    name: cargo machete
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
        with:
          just-version: 0.10.5

      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo install cargo-machete

      - run: just machete
