name: cargo test

on:
  merge_group:
  pull_request:

jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
        with:
          just-version: 0.10.5

      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: just test
